### PR TITLE
lang: Fix string escapes

### LINKED ISSUE #94: Fix string escapes when parsing moldfiles
Escapes like `\n \r \t` don't work.

### PR DESCRIPTION
**Pull request by scizzorz**
Fix #94

### CODE REVIEW

File: src/lang.rs [hunk 1]
```diff
@@ -127,7 +127,33 @@ fn consume_string(pairs: &mut Pairs<Rule>) -> Option<String> {
...
     .next()
     .and_then(|x| x.into_inner().next())
-    .map(|x| x.as_str().to_string())
+    .map(|x| unescape(x.as_str()))
+}
+
+/// Given a &str, unescape special characters
+///
+/// This should potentially return an error, but that really complicates the
+/// above API, so it just silently permits and ignores invalid escapes. Oops.
```
Comment (philipdexter) [inline src/lang.rs:136]: :fearful:

**Review by philipdexter — APPROVED** [review]

File: src/lang.rs (hunk 1 above)
Comment (scizzorz) [reply src/lang.rs:136]: Yeah. I'll reach into fixing this up later, but for now I'm letting it slide.
